[tool.poetry]
name = "sentimental"
version = "0.1.0"
description = ""
authors = ["nikhil"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "2.0.1"
pyngrok = "5.1.0"
joblib = "1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
